version: "3.8"

services:
  api:
    build:
      context: ./ml-prediction
      dockerfile: Dockerfile
    volumes:
      - ./ml-prediction:/app:delegated
    command: uvicorn server:app --host 0.0.0.0 --port 3001 --reload
    environment:
      - PYTHONUNBUFFERED=1

  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./web:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install --silent && npm run dev"
