version: "3.8"

services:
  api:
    build:
      context: ./ml-prediction
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - exo-explorer-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - exo-explorer-network

networks:
  exo-explorer-network:
    driver: bridge
